name: Deploy Lambda Container

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin 173534767554.dkr.ecr.us-east-1.amazonaws.com

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 173534767554.dkr.ecr.us-east-1.amazonaws.com
          IMAGE_REPO_NAME: pi6-airplay-knn
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG

      - name: Update Lambda function to use new image
        env:
          ECR_REGISTRY: 173534767554.dkr.ecr.us-east-1.amazonaws.com
          IMAGE_REPO_NAME: pi6-airplay-knn
          IMAGE_TAG: latest
        run: |
          aws lambda update-function-code \
            --function-name pi6-airplay-knn \
            --image-uri $ECR_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG